let a;
try {
  a = 3;
} catch (error) {
  return error;
}

console.log(a);
